spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: dbo
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  secret: ${JWT_SECRET}
  access-expiration-millis: 300000
  refresh-expiration-millis: 900000
