server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DB_AuthService
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600}

logging:
  level:
    org.springframework.security: DEBUG
