spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=DB_AuthService;encrypt=false;trustServerCertificate=true
    username: sa
    password: sql
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: dbo
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  secret: Y16Y9Kp3eX7Q53U9v1yph0K3NaiypABC
  access-expiration-millis: 300000       # 5 min
  refresh-expiration-millis: 900000      # 15 min